### PR TITLE
Fixed typos in pdf

### LINKED ISSUE #1: Avatars converted to glTF and multi-users example on the web
Thank you for making those avatars available with a MIT license!

I wrote a multi-users example with [A-Frame](https://aframe.io) (that's using [threejs](https://threejs.org/)) and [networked-aframe](https://github.com/networked-aframe/networked-aframe) with a UI to select the avatar and I added an idle and walking animations on those avatars, you can see yourself in a mirror.
Demo: https://naf-valid-avatars.glitch.me/
GitHub: https://github.com/networked-aframe/naf-valid-avatars

To be able to use those avatars I converted in https://github.com/c-frame/valid-avatars-glb the 200 avatars from fbx to glb with blender and gltf-transform optimize with meshopt compression reducing the size by two (see scripts folder in the repo if you're curious), and also extracted all images from the pdf and produced a json file with all the avatars and path to the image and glb.

Some mistakes I found in your pdf:
- MENA_1_Casual missing the gender, should be MENA_M_1_Casual
- Mena instead of MENA on some texts
- x_ instead of X_ on some texts
- There are images for X_AIAN_F_2_* but the following fbx files don't exist in the repo:
  X_Non-validated/X_AIAN_F_2_Casual.fbx
  X_Non-validated/X_AIAN_F_2_Busi.fbx
  X_Non-validated/X_AIAN_F_2_Medi.fbx
  X_Non-validated/X_AIAN_F_2_Milit.fbx
  X_Non-validated/X_AIAN_F_2_Util.fbx
  
If you do other avatars in the future, please consider putting all the images in a folder with the same name as the fbx file, that would be awesome.

### PR DESCRIPTION
**Pull request by Zyrcant**

### CODE REVIEW

**Comment by vincentfretin** [comment]
If I look at the two pdf versions, I see you changed
Hispanic_F_3_Casual to MENA_F_3_Casual
Hispanic_F_3_Busi to MENA_F_3_Busi
Was it intentional? If you rename those, you probably want to rename the fbx files as well.
Also what about Hispanic_F_2_Casual and Hispanic_F_2_Busi? Is this also a mistake in this case? Should those be renamed?

**Comment by vincentfretin** [comment]
FYI the pdf increased from 3.1MB to 7.8MB. The extracted images from my Python script with this pdf are of the same dimensions but are indeed bigger in file size. I'm not sure if you created the pdf differently this time, anyway that doesn't matter much. I'll keep the old pdf for my script, just renaming X_AIAN_F_2 to X_AIAN_F_1 that was the only remaining issue.

**Comment by vincentfretin** [comment]
I found 6 errors with the image text MENA_M_2_* and MENA_M_3_* are duplicated
From the fbx files, it should be Hispanic_F_2_* and Hispanic_F_3_* for the the first and second lines in page 5.
With those changes, I get all the 210 avatars with images with my script.

**Comment by Zyrcant** [comment]
My sincere apologies for the additional typos!  I must have edited an old version of the PDF. Many thanks for catching these typos.

I just fixed it and double and triple checked this time for sure. The pdf should be fixed _for real this time_. 

As for the size discrepancy-- I generated the pdf using Adobe Indesign, and I'm not quite sure what compression magic it does. In retrospect, I should have written a script to generate a markdown document of avatar previews, which would have been a lot faster and have less user error like typos... Perhaps it'll be something I work on in the near future, since we do have some new avatars planned for release in the upcoming months.

**Comment by vincentfretin** [comment]
I'm really sorry, but you forgot to change the gender on those three:
Hispanic_M_2_Medi => Hispanic_F_2_Medi
Hispanic_M_2_Milit => Hispanic_F_2_Milit
Hispanic_M_2_Util => Hispanic_F_2_Util

**Comment by Zyrcant** [comment]
Fixed! :')

**Pull request merged**
